package model;
// Generated Oct 24, 2014 1:11:37 AM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Colors generated by hbm2java
 */
public class Colors  implements java.io.Serializable {


     private BigDecimal colorId;
     private String colorName;
     private Set transactionDetailses = new HashSet(0);
     private Set itemsSerialses = new HashSet(0);

    public Colors() {
    }

	
    public Colors(BigDecimal colorId) {
        this.colorId = colorId;
    }
    public Colors(BigDecimal colorId, String colorName, Set transactionDetailses, Set itemsSerialses) {
       this.colorId = colorId;
       this.colorName = colorName;
       this.transactionDetailses = transactionDetailses;
       this.itemsSerialses = itemsSerialses;
    }
   
    public BigDecimal getColorId() {
        return this.colorId;
    }
    
    public void setColorId(BigDecimal colorId) {
        this.colorId = colorId;
    }
    public String getColorName() {
        return this.colorName;
    }
    
    public void setColorName(String colorName) {
        this.colorName = colorName;
    }
    public Set getTransactionDetailses() {
        return this.transactionDetailses;
    }
    
    public void setTransactionDetailses(Set transactionDetailses) {
        this.transactionDetailses = transactionDetailses;
    }
    public Set getItemsSerialses() {
        return this.itemsSerialses;
    }
    
    public void setItemsSerialses(Set itemsSerialses) {
        this.itemsSerialses = itemsSerialses;
    }




}


