package model;
// Generated Nov 14, 2014 12:02:34 AM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * CostCenter generated by hbm2java
 */
public class CostCenter  implements java.io.Serializable {


     private BigDecimal costCenterId;
     private Users users;
     private String costCenterName;
     private Set chartses = new HashSet(0);

    public CostCenter() {
    }

	
    public CostCenter(BigDecimal costCenterId) {
        this.costCenterId = costCenterId;
    }
    public CostCenter(BigDecimal costCenterId, Users users, String costCenterName, Set chartses) {
       this.costCenterId = costCenterId;
       this.users = users;
       this.costCenterName = costCenterName;
       this.chartses = chartses;
    }
   
    public BigDecimal getCostCenterId() {
        return this.costCenterId;
    }
    
    public void setCostCenterId(BigDecimal costCenterId) {
        this.costCenterId = costCenterId;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getCostCenterName() {
        return this.costCenterName;
    }
    
    public void setCostCenterName(String costCenterName) {
        this.costCenterName = costCenterName;
    }
    public Set getChartses() {
        return this.chartses;
    }
    
    public void setChartses(Set chartses) {
        this.chartses = chartses;
    }




}


