package model;
// Generated Nov 14, 2014 12:02:34 AM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Employees generated by hbm2java
 */
public class Employees  implements java.io.Serializable {


     private BigDecimal empId;
     private Users users;
     private Charts charts;
     private String empName;
     private String empPhone;
     private String empPhone2;
     private Double salary;
     private Double commision;
     private Set transactionses = new HashSet(0);
     private Set storeses = new HashSet(0);
     private String info;
     private Date hireDate;

    public Employees() {
    }

	
    public Employees(BigDecimal empId) {
        this.empId = empId;
    }
    public Employees(BigDecimal empId, Users users, Charts charts, String empName, String empPhone, String empPhone2, Double salary, Double commision,
            Set transactionses, Set storeses, String info, Date hireDate) {
       this.empId = empId;
       this.users = users;
       this.charts = charts;
       this.empName = empName;
       this.empPhone = empPhone;
       this.empPhone2 = empPhone2;
       this.salary = salary;
       this.commision = commision;
       this.transactionses = transactionses;
       this.storeses = storeses;
       this.info = info;
       this.hireDate = hireDate;
    }
   
    public BigDecimal getEmpId() {
        return this.empId;
    }
    
    public void setEmpId(BigDecimal empId) {
        this.empId = empId;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public Charts getCharts() {
        return this.charts;
    }
    
    public void setCharts(Charts charts) {
        this.charts = charts;
    }
    public String getEmpName() {
        return this.empName;
    }
    
    public void setEmpName(String empName) {
        this.empName = empName;
    }
    public String getEmpPhone() {
        return this.empPhone;
    }
    
    public void setEmpPhone(String empPhone) {
        this.empPhone = empPhone;
    }
    public String getEmpPhone2() {
        return this.empPhone2;
    }
    
    public void setEmpPhone2(String empPhone2) {
        this.empPhone2 = empPhone2;
    }
    public Double getSalary() {
        return this.salary;
    }
    
    public void setSalary(Double salary) {
        this.salary = salary;
    }
    public Double getCommision() {
        return this.commision;
    }
    
    public void setCommision(Double commision) {
        this.commision = commision;
    }
    public Set getTransactionses() {
        return this.transactionses;
    }
    
    public void setTransactionses(Set transactionses) {
        this.transactionses = transactionses;
    }
    public Set getStoreses() {
        return this.storeses;
    }
    
    public void setStoreses(Set storeses) {
        this.storeses = storeses;
    }

    public String getInfo() {
        return info;
    }

    public void setInfo(String info) {
        this.info = info;
    }

    public Date getHireDate() {
        return hireDate;
    }

    public void setHireDate(Date hireDate) {
        this.hireDate = hireDate;
    }

    


}


