package model;
// Generated Nov 14, 2014 12:02:34 AM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Function generated by hbm2java
 */
public class Function  implements java.io.Serializable {


     private BigDecimal id;
     private String functionId;
     private String name;
     private String description;
     private Set roleFunctions = new HashSet(0);

    public Function() {
    }

	
    public Function(BigDecimal id) {
        this.id = id;
    }
    public Function(BigDecimal id, String functionId, String name, String description, Set roleFunctions) {
       this.id = id;
       this.functionId = functionId;
       this.name = name;
       this.description = description;
       this.roleFunctions = roleFunctions;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public String getFunctionId() {
        return this.functionId;
    }
    
    public void setFunctionId(String functionId) {
        this.functionId = functionId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getRoleFunctions() {
        return this.roleFunctions;
    }
    
    public void setRoleFunctions(Set roleFunctions) {
        this.roleFunctions = roleFunctions;
    }




}


