package model;
// Generated Oct 24, 2014 1:11:37 AM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Groups generated by hbm2java
 */
public class Groups  implements java.io.Serializable {


     private BigDecimal groupId;
     private String groupName;
     private Set itemses = new HashSet(0);

    public Groups() {
    }

	
    public Groups(BigDecimal groupId) {
        this.groupId = groupId;
    }
    public Groups(BigDecimal groupId, String groupName, Set itemses) {
       this.groupId = groupId;
       this.groupName = groupName;
       this.itemses = itemses;
    }
   
    public BigDecimal getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(BigDecimal groupId) {
        this.groupId = groupId;
    }
    public String getGroupName() {
        return this.groupName;
    }
    
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }
    public Set getItemses() {
        return this.itemses;
    }
    
    public void setItemses(Set itemses) {
        this.itemses = itemses;
    }




}


