package model;
// Generated Nov 14, 2014 12:02:34 AM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.sql.Blob;
import java.util.HashSet;
import java.util.Set;

/**
 * Items generated by hbm2java
 */
public class Items  implements java.io.Serializable {


     private BigDecimal itemId;
     private Users users;
     private Types types;
     private Persons persons;
     private Groups groups;
     private Sections sections;
     private Units units;
     private String itemName;
     private String itemNotes;
     private String itemPic;
     private Set itemsSerialses = new HashSet(0);
     private BigDecimal productType;
    public Items() {
    }

	
    public Items(BigDecimal itemId) {
        this.itemId = itemId;
    }
    public Items(BigDecimal itemId, Users users, Types types, Persons persons, Groups groups, Sections sections, Units units, String itemName, String itemNotes, String barCode, String itemPic, Set itemsSerialses, BigDecimal productType) {
       this.itemId = itemId;
       this.users = users;
       this.types = types;
       this.persons = persons;
       this.groups = groups;
       this.sections = sections;
       this.units = units;
       this.itemName = itemName;
       this.itemNotes = itemNotes;
       this.itemPic = itemPic;
       this.itemsSerialses = itemsSerialses;
       this.productType = productType;
    }
   
    public BigDecimal getItemId() {
        return this.itemId;
    }
    
    public void setItemId(BigDecimal itemId) {
        this.itemId = itemId;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public Types getTypes() {
        return this.types;
    }
    
    public void setTypes(Types types) {
        this.types = types;
    }
    public Persons getPersons() {
        return this.persons;
    }
    
    public void setPersons(Persons persons) {
        this.persons = persons;
    }
    public Groups getGroups() {
        return this.groups;
    }
    
    public void setGroups(Groups groups) {
        this.groups = groups;
    }
    public Sections getSections() {
        return this.sections;
    }
    
    public void setSections(Sections sections) {
        this.sections = sections;
    }
    public Units getUnits() {
        return this.units;
    }
    
    public void setUnits(Units units) {
        this.units = units;
    }
    public String getItemName() {
        return this.itemName;
    }
    
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }
    public String getItemNotes() {
        return this.itemNotes;
    }
    
    public void setItemNotes(String itemNotes) {
        this.itemNotes = itemNotes;
    }

    public String getItemPic() {
        return this.itemPic;
    }
    
    public void setItemPic(String itemPic) {
        this.itemPic = itemPic;
    }
    public Set getItemsSerialses() {
        return this.itemsSerialses;
    }
    
    public void setItemsSerialses(Set itemsSerialses) {
        this.itemsSerialses = itemsSerialses;
    }

    public BigDecimal getProductType() {
        return productType;
    }

    public void setProductType(BigDecimal productType) {
        this.productType = productType;
    }

    


}


