package model;
// Generated Nov 14, 2014 12:02:34 AM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Persons generated by hbm2java
 */
public class Persons  implements java.io.Serializable {


     private PersonsId id;
     private Users users;
     private Zone zone;
     private Department department;
     private Charts charts;
     private String personName;
     private String companyName;
     private String personPhone;
     private String personPhone2;
     private String personAddress;
     private String notes;
     private Double openDebit;
     private Double openCredit;
     private Double maxBalance;
     private String contactName;
     private String contactPhone;
     private BigDecimal transType;
     private String pesronEmail;
     private Set transactionses = new HashSet(0);
     private Set portfolios = new HashSet(0);
     private Set itemses = new HashSet(0);

    public Persons() {
    }

	
    public Persons(PersonsId id) {
        this.id = id;
    }
    public Persons(PersonsId id, Users users, Zone zone, Department department, Charts charts, String personName, String companyName, String personPhone, String personPhone2, String personAddress, String notes, Double openDebit, Double openCredit, Double maxBalance, String contactName, String contactPhone, BigDecimal transType, String pesronEmail, Set transactionses, Set portfolios, Set itemses) {
       this.id = id;
       this.users = users;
       this.zone = zone;
       this.department = department;
       this.charts = charts;
       this.personName = personName;
       this.companyName = companyName;
       this.personPhone = personPhone;
       this.personPhone2 = personPhone2;
       this.personAddress = personAddress;
       this.notes = notes;
       this.openDebit = openDebit;
       this.openCredit = openCredit;
       this.maxBalance = maxBalance;
       this.contactName = contactName;
       this.contactPhone = contactPhone;
       this.transType = transType;
       this.pesronEmail = pesronEmail;
       this.transactionses = transactionses;
       this.portfolios = portfolios;
       this.itemses = itemses;
    }
   
    public PersonsId getId() {
        return this.id;
    }
    
    public void setId(PersonsId id) {
        this.id = id;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public Zone getZone() {
        return this.zone;
    }
    
    public void setZone(Zone zone) {
        this.zone = zone;
    }
    public Department getDepartment() {
        return this.department;
    }
    
    public void setDepartment(Department department) {
        this.department = department;
    }
    public Charts getCharts() {
        return this.charts;
    }
    
    public void setCharts(Charts charts) {
        this.charts = charts;
    }
    public String getPersonName() {
        return this.personName;
    }
    
    public void setPersonName(String personName) {
        this.personName = personName;
    }
    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }
    public String getPersonPhone() {
        return this.personPhone;
    }
    
    public void setPersonPhone(String personPhone) {
        this.personPhone = personPhone;
    }
    public String getPersonPhone2() {
        return this.personPhone2;
    }
    
    public void setPersonPhone2(String personPhone2) {
        this.personPhone2 = personPhone2;
    }
    public String getPersonAddress() {
        return this.personAddress;
    }
    
    public void setPersonAddress(String personAddress) {
        this.personAddress = personAddress;
    }
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }
    public Double getOpenDebit() {
        return this.openDebit;
    }
    
    public void setOpenDebit(Double openDebit) {
        this.openDebit = openDebit;
    }
    public Double getOpenCredit() {
        return this.openCredit;
    }
    
    public void setOpenCredit(Double openCredit) {
        this.openCredit = openCredit;
    }
    public Double getMaxBalance() {
        return this.maxBalance;
    }
    
    public void setMaxBalance(Double maxBalance) {
        this.maxBalance = maxBalance;
    }
    public String getContactName() {
        return this.contactName;
    }
    
    public void setContactName(String contactName) {
        this.contactName = contactName;
    }
    public String getContactPhone() {
        return this.contactPhone;
    }
    
    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone;
    }
    public BigDecimal getTransType() {
        return this.transType;
    }
    
    public void setTransType(BigDecimal transType) {
        this.transType = transType;
    }
    public String getPesronEmail() {
        return this.pesronEmail;
    }
    
    public void setPesronEmail(String pesronEmail) {
        this.pesronEmail = pesronEmail;
    }
    public Set getTransactionses() {
        return this.transactionses;
    }
    
    public void setTransactionses(Set transactionses) {
        this.transactionses = transactionses;
    }
    public Set getPortfolios() {
        return this.portfolios;
    }
    
    public void setPortfolios(Set portfolios) {
        this.portfolios = portfolios;
    }
    public Set getItemses() {
        return this.itemses;
    }
    
    public void setItemses(Set itemses) {
        this.itemses = itemses;
    }

    @Override
    public String toString() {
        return this.personName; //To change body of generated methods, choose Tools | Templates.
    }




}


