package model;
// Generated Nov 14, 2014 12:02:34 AM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PortfolioDetails generated by hbm2java
 */
public class PortfolioDetails  implements java.io.Serializable {


     private BigDecimal portDId;
     private Portfolio portfolio;
     private BigDecimal noteNumber;
     private BigDecimal noteKind;
     private Date noteDate;
     private String nameNote;
     private BigDecimal noteAmount;
     private Set transactionDetailses = new HashSet(0);

    public PortfolioDetails() {
    }

	
    public PortfolioDetails(BigDecimal portDId) {
        this.portDId = portDId;
    }
    public PortfolioDetails(BigDecimal portDId, Portfolio portfolio, BigDecimal noteNumber, BigDecimal noteKind, Date noteDate, String nameNote, BigDecimal noteAmount, Set transactionDetailses) {
       this.portDId = portDId;
       this.portfolio = portfolio;
       this.noteNumber = noteNumber;
       this.noteKind = noteKind;
       this.noteDate = noteDate;
       this.nameNote = nameNote;
       this.noteAmount = noteAmount;
       this.transactionDetailses = transactionDetailses;
    }
   
    public BigDecimal getPortDId() {
        return this.portDId;
    }
    
    public void setPortDId(BigDecimal portDId) {
        this.portDId = portDId;
    }
    public Portfolio getPortfolio() {
        return this.portfolio;
    }
    
    public void setPortfolio(Portfolio portfolio) {
        this.portfolio = portfolio;
    }
    public BigDecimal getNoteNumber() {
        return this.noteNumber;
    }
    
    public void setNoteNumber(BigDecimal noteNumber) {
        this.noteNumber = noteNumber;
    }
    public BigDecimal getNoteKind() {
        return this.noteKind;
    }
    
    public void setNoteKind(BigDecimal noteKind) {
        this.noteKind = noteKind;
    }
    public Date getNoteDate() {
        return this.noteDate;
    }
    
    public void setNoteDate(Date noteDate) {
        this.noteDate = noteDate;
    }
    public String getNameNote() {
        return this.nameNote;
    }
    
    public void setNameNote(String nameNote) {
        this.nameNote = nameNote;
    }
    public BigDecimal getNoteAmount() {
        return this.noteAmount;
    }
    
    public void setNoteAmount(BigDecimal noteAmount) {
        this.noteAmount = noteAmount;
    }
    public Set getTransactionDetailses() {
        return this.transactionDetailses;
    }
    
    public void setTransactionDetailses(Set transactionDetailses) {
        this.transactionDetailses = transactionDetailses;
    }




}


