package model;
// Generated Nov 14, 2014 12:02:34 AM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Portfolio generated by hbm2java
 */
public class Portfolio  implements java.io.Serializable {


     private PortfolioId id;
     private Users users;
     private Persons persons;
     private Date portDate;
     private BigDecimal protfolioAmount;
     private String portNotes;
     private Set portfolioDetailses = new HashSet(0);

    public Portfolio() {
    }

	
    public Portfolio(PortfolioId id) {
        this.id = id;
    }
    public Portfolio(PortfolioId id, Users users, Persons persons, Date portDate, BigDecimal protfolioAmount, String portNotes, Set portfolioDetailses) {
       this.id = id;
       this.users = users;
       this.persons = persons;
       this.portDate = portDate;
       this.protfolioAmount = protfolioAmount;
       this.portNotes = portNotes;
       this.portfolioDetailses = portfolioDetailses;
    }
   
    public PortfolioId getId() {
        return this.id;
    }
    
    public void setId(PortfolioId id) {
        this.id = id;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public Persons getPersons() {
        return this.persons;
    }
    
    public void setPersons(Persons persons) {
        this.persons = persons;
    }
    public Date getPortDate() {
        return this.portDate;
    }
    
    public void setPortDate(Date portDate) {
        this.portDate = portDate;
    }
    public BigDecimal getProtfolioAmount() {
        return this.protfolioAmount;
    }
    
    public void setProtfolioAmount(BigDecimal protfolioAmount) {
        this.protfolioAmount = protfolioAmount;
    }
    public String getPortNotes() {
        return this.portNotes;
    }
    
    public void setPortNotes(String portNotes) {
        this.portNotes = portNotes;
    }
    public Set getPortfolioDetailses() {
        return this.portfolioDetailses;
    }
    
    public void setPortfolioDetailses(Set portfolioDetailses) {
        this.portfolioDetailses = portfolioDetailses;
    }




}


