package model;
// Generated Nov 14, 2014 12:02:34 AM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by hbm2java
 */
public class Role  implements java.io.Serializable {


     private BigDecimal roleId;
     private String name;
     private String description;
     private Set roleFunctions = new HashSet(0);
     private Set userses = new HashSet(0);

    public Role() {
    }

	
    public Role(BigDecimal roleId) {
        this.roleId = roleId;
    }
    public Role(BigDecimal roleId, String name, String description, Set roleFunctions, Set userses) {
       this.roleId = roleId;
       this.name = name;
       this.description = description;
       this.roleFunctions = roleFunctions;
       this.userses = userses;
    }
   
    public BigDecimal getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(BigDecimal roleId) {
        this.roleId = roleId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getRoleFunctions() {
        return this.roleFunctions;
    }
    
    public void setRoleFunctions(Set roleFunctions) {
        this.roleFunctions = roleFunctions;
    }
    public Set getUserses() {
        return this.userses;
    }
    
    public void setUserses(Set userses) {
        this.userses = userses;
    }




}


