package model;
// Generated Nov 14, 2014 12:02:34 AM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Transactions generated by hbm2java
 */
public class Transactions  implements java.io.Serializable {


     private TransactionsId id;
     private Users users;
     private Stores stores;
     private Persons persons;
     private Employees employees;
     private Banks banks;
     private Expences expences;
     private BigDecimal transWsid;
     private Date transDate;
     private BigDecimal transDiscPercent;
     private BigDecimal transDiscValue;
     private String transVisa;
     private String transNote;
     private BigDecimal taxPercent;
     private BigDecimal taxValue;
     private Set transactionDetailses = new HashSet(0);

    public Transactions() {
    }

	
    public Transactions(TransactionsId id) {
        this.id = id;
    }
    public Transactions(TransactionsId id, Users users, Stores stores, Persons persons, Employees employees, Banks banks, Expences expences, BigDecimal transWsid, Date transDate, BigDecimal transDiscPercent, BigDecimal transDiscValue, String transVisa, String transNote, BigDecimal taxPercent, BigDecimal taxValue, Set transactionDetailses) {
       this.id = id;
       this.users = users;
       this.stores = stores;
       this.persons = persons;
       this.employees = employees;
       this.banks = banks;
       this.expences = expences;
       this.transWsid = transWsid;
       this.transDate = transDate;
       this.transDiscPercent = transDiscPercent;
       this.transDiscValue = transDiscValue;
       this.transVisa = transVisa;
       this.transNote = transNote;
       this.taxPercent = taxPercent;
       this.taxValue = taxValue;
       this.transactionDetailses = transactionDetailses;
    }
   
    public TransactionsId getId() {
        return this.id;
    }
    
    public void setId(TransactionsId id) {
        this.id = id;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public Stores getStores() {
        return this.stores;
    }
    
    public void setStores(Stores stores) {
        this.stores = stores;
    }
    public Persons getPersons() {
        return this.persons;
    }
    
    public void setPersons(Persons persons) {
        this.persons = persons;
    }
    public Employees getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Employees employees) {
        this.employees = employees;
    }
    public Banks getBanks() {
        return this.banks;
    }
    
    public void setBanks(Banks banks) {
        this.banks = banks;
    }
    public Expences getExpences() {
        return this.expences;
    }
    
    public void setExpences(Expences expences) {
        this.expences = expences;
    }
    public BigDecimal getTransWsid() {
        return this.transWsid;
    }
    
    public void setTransWsid(BigDecimal transWsid) {
        this.transWsid = transWsid;
    }
    public Date getTransDate() {
        return this.transDate;
    }
    
    public void setTransDate(Date transDate) {
        this.transDate = transDate;
    }
    public BigDecimal getTransDiscPercent() {
        return this.transDiscPercent;
    }
    
    public void setTransDiscPercent(BigDecimal transDiscPercent) {
        this.transDiscPercent = transDiscPercent;
    }
    public BigDecimal getTransDiscValue() {
        return this.transDiscValue;
    }
    
    public void setTransDiscValue(BigDecimal transDiscValue) {
        this.transDiscValue = transDiscValue;
    }
    public String getTransVisa() {
        return this.transVisa;
    }
    
    public void setTransVisa(String transVisa) {
        this.transVisa = transVisa;
    }
    public String getTransNote() {
        return this.transNote;
    }
    
    public void setTransNote(String transNote) {
        this.transNote = transNote;
    }
    public BigDecimal getTaxPercent() {
        return this.taxPercent;
    }
    
    public void setTaxPercent(BigDecimal taxPercent) {
        this.taxPercent = taxPercent;
    }
    public BigDecimal getTaxValue() {
        return this.taxValue;
    }
    
    public void setTaxValue(BigDecimal taxValue) {
        this.taxValue = taxValue;
    }
    public Set getTransactionDetailses() {
        return this.transactionDetailses;
    }
    
    public void setTransactionDetailses(Set transactionDetailses) {
        this.transactionDetailses = transactionDetailses;
    }




}


