package model;
// Generated Oct 24, 2014 1:11:37 AM by Hibernate Tools 3.6.0


import java.math.BigDecimal;

/**
 * TransactionsId generated by hbm2java
 */
public class TransactionsId  implements java.io.Serializable {


     private BigDecimal transNo;
     private BigDecimal transType;

    public TransactionsId() {
    }

    public TransactionsId(BigDecimal transNo, BigDecimal transType) {
       this.transNo = transNo;
       this.transType = transType;
    }
   
    public BigDecimal getTransNo() {
        return this.transNo;
    }
    
    public void setTransNo(BigDecimal transNo) {
        this.transNo = transNo;
    }
    public BigDecimal getTransType() {
        return this.transType;
    }
    
    public void setTransType(BigDecimal transType) {
        this.transType = transType;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TransactionsId) ) return false;
		 TransactionsId castOther = ( TransactionsId ) other; 
         
		 return ( (this.getTransNo()==castOther.getTransNo()) || ( this.getTransNo()!=null && castOther.getTransNo()!=null && this.getTransNo().equals(castOther.getTransNo()) ) )
 && ( (this.getTransType()==castOther.getTransType()) || ( this.getTransType()!=null && castOther.getTransType()!=null && this.getTransType().equals(castOther.getTransType()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTransNo() == null ? 0 : this.getTransNo().hashCode() );
         result = 37 * result + ( getTransType() == null ? 0 : this.getTransType().hashCode() );
         return result;
   }   


}


