package model;
// Generated Oct 24, 2014 1:11:37 AM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Units generated by hbm2java
 */
public class Units  implements java.io.Serializable {


     private BigDecimal unitId;
     private String unitName;
     private Set itemses = new HashSet(0);

    public Units() {
    }

	
    public Units(BigDecimal unitId) {
        this.unitId = unitId;
    }
    public Units(BigDecimal unitId, String unitName, Set itemses) {
       this.unitId = unitId;
       this.unitName = unitName;
       this.itemses = itemses;
    }
   
    public BigDecimal getUnitId() {
        return this.unitId;
    }
    
    public void setUnitId(BigDecimal unitId) {
        this.unitId = unitId;
    }
    public String getUnitName() {
        return this.unitName;
    }
    
    public void setUnitName(String unitName) {
        this.unitName = unitName;
    }
    public Set getItemses() {
        return this.itemses;
    }
    
    public void setItemses(Set itemses) {
        this.itemses = itemses;
    }




}


