package model;
// Generated Oct 24, 2014 1:11:37 AM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private BigDecimal id;
     private Role role;
     private String name;
     private String userName;
     private String password;
     private BigDecimal userType;
     private Set storeses = new HashSet(0);
     private Set bankses = new HashSet(0);
     private Set costCenters = new HashSet(0);
     private Set employeeses = new HashSet(0);
     private Set expenceses = new HashSet(0);
     private Set itemses = new HashSet(0);
     private Set portfolios = new HashSet(0);
     private Set transactionses = new HashSet(0);
     private Set chartses = new HashSet(0);
     private Set personses = new HashSet(0);

    public Users() {
    }

	
    public Users(BigDecimal id) {
        this.id = id;
    }
    public Users(BigDecimal id, Role role, String name, String userName, String password, BigDecimal userType, Set storeses, Set bankses, Set costCenters, Set employeeses, Set expenceses, Set itemses, Set portfolios, Set transactionses, Set chartses, Set personses) {
       this.id = id;
       this.role = role;
       this.name = name;
       this.userName = userName;
       this.password = password;
       this.userType = userType;
       this.storeses = storeses;
       this.bankses = bankses;
       this.costCenters = costCenters;
       this.employeeses = employeeses;
       this.expenceses = expenceses;
       this.itemses = itemses;
       this.portfolios = portfolios;
       this.transactionses = transactionses;
       this.chartses = chartses;
       this.personses = personses;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public BigDecimal getUserType() {
        return this.userType;
    }
    
    public void setUserType(BigDecimal userType) {
        this.userType = userType;
    }
    public Set getStoreses() {
        return this.storeses;
    }
    
    public void setStoreses(Set storeses) {
        this.storeses = storeses;
    }
    public Set getBankses() {
        return this.bankses;
    }
    
    public void setBankses(Set bankses) {
        this.bankses = bankses;
    }
    public Set getCostCenters() {
        return this.costCenters;
    }
    
    public void setCostCenters(Set costCenters) {
        this.costCenters = costCenters;
    }
    public Set getEmployeeses() {
        return this.employeeses;
    }
    
    public void setEmployeeses(Set employeeses) {
        this.employeeses = employeeses;
    }
    public Set getExpenceses() {
        return this.expenceses;
    }
    
    public void setExpenceses(Set expenceses) {
        this.expenceses = expenceses;
    }
    public Set getItemses() {
        return this.itemses;
    }
    
    public void setItemses(Set itemses) {
        this.itemses = itemses;
    }
    public Set getPortfolios() {
        return this.portfolios;
    }
    
    public void setPortfolios(Set portfolios) {
        this.portfolios = portfolios;
    }
    public Set getTransactionses() {
        return this.transactionses;
    }
    
    public void setTransactionses(Set transactionses) {
        this.transactionses = transactionses;
    }
    public Set getChartses() {
        return this.chartses;
    }
    
    public void setChartses(Set chartses) {
        this.chartses = chartses;
    }
    public Set getPersonses() {
        return this.personses;
    }
    
    public void setPersonses(Set personses) {
        this.personses = personses;
    }




}


