package model;
// Generated Nov 14, 2014 12:02:34 AM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Zone generated by hbm2java
 */
public class Zone  implements java.io.Serializable {


     private BigDecimal zoneId;
     private String zoneName;
     private Set personses = new HashSet(0);

    public Zone() {
    }

	
    public Zone(BigDecimal zoneId) {
        this.zoneId = zoneId;
    }
    public Zone(BigDecimal zoneId, String zoneName, Set personses) {
       this.zoneId = zoneId;
       this.zoneName = zoneName;
       this.personses = personses;
    }
   
    public BigDecimal getZoneId() {
        return this.zoneId;
    }
    
    public void setZoneId(BigDecimal zoneId) {
        this.zoneId = zoneId;
    }
    public String getZoneName() {
        return this.zoneName;
    }
    
    public void setZoneName(String zoneName) {
        this.zoneName = zoneName;
    }
    public Set getPersonses() {
        return this.personses;
    }
    
    public void setPersonses(Set personses) {
        this.personses = personses;
    }




}


